### ISSUE TITLE
关于数据，及数据处理程序

### ISSUE THREAD

**Issue by liheyong** [Zziwei/Joint-Collaborative-Autoencoder#2]
您好！从您的数据处理程序看，您的数据应该没有完全提供啊，打开数据也都是用户id和对应的项目id,没有评分一栏的数据。这样的话，用不上啊。

**Comment by Zziwei** [comment]
Hi, the data files provided are already preprocessed. You do not need to run the data processing code again on them, and just use the data to run the model code.
